### ISSUE TITLE
Проблемка с сортировкой

### ISSUE THREAD

**Issue by acnapd** [lers-uchet/LersBot#10]
Точки учёта/Объекты с именами начинающимися с цифры отсортированы неверно, после '19' идёт '2', после '29' идёт '3'
![default](https://user-images.githubusercontent.com/33048914/32574247-a6e9a0b2-c4e1-11e7-8411-8272ddfb1b37.png)

**Comment by achikhv** [comment]
Это потому что используется стандартная сортировка, а не [естественная](https://en.wikipedia.org/wiki/Natural_sort_order). 
Поставлю в план на следующий релиз. Возможно, к R24 добавлю.

**Comment by achikhv** [comment]
В текущей версии бота используется естественная сортировка.
