### ISSUE TITLE
Поправить поиск (Аргументы)

### ISSUE THREAD

**Issue by kumhak** [lers-uchet/LersBot#12]
Добавить возможность использовать аргументы при поиске.
Сейчас при запросе списка точек либо текущих параметров точки есть вероятность получить в выдаче результаты по другим точкам.

**Comment by achikhv** [comment]
Сейчас параметры поиска всегда разделяются пробелами. Нужно добавить поддержку кавычек, в которых можно будет указать строку с пробелами, которая будет считаться одной подстрокой для поиска. Тогда для поиска можно будет набрать **"Адрес 2"** и это должно считаться одной строкой, а не двумя.

**Comment by achikhv** [comment]
В релизе версии v0.25.2 бот понимает аргументы командной строки в кавычках.
