### ISSUE TITLE
В сообщении вместо показаний отображается строка "Lers.Data.ValueAndAttributes"

### ISSUE THREAD

**Issue by slavniylers** [lers-uchet/LersBot#14]
При опросе текущих в сообщении бота вместо показаний отображается строка "Lers.Data.ValueAndAttributes" по каждому параметру.

Подробнее в соответствующей [теме](http://forum.lers.ru/viewtopic.php?f=23&t=6780) форума.

**Comment by Werzet** [comment]
Вывод сообщений исправлен.
