### ISSUE TITLE
Не запускается служба поддержки сообщений Telegram

### ISSUE THREAD

**Issue by lishuk** [lers-uchet/LersBot#16]
А из-за чего бот может не подключиться к серверу и как проверить подключение?
Я всё делал по Вашей инструкции, но единственное, при запуске службы "ЛЭРС учет - Служба поддержки сообщений Telegram" система выдает сообщение:
Служба "ЛЭРС учет - Служба поддержки сообщений Telegram" на "Локальный компьютер" была запущена и затем остановлена. Некоторые службы автоматически останавливаются, если они не используются другими службами или программами

**Comment by achikhv** [comment]
В связи с тем, что блокиировки Telegram прекратились, мы возобновим проект. Новый бот будет опубликован после выхода версии 3.36.
В связи с этим, проблемы со старыми версиями разбирать не имеет смысла. Новый бот будет запускаться и  работать на ЛЭРС УЧЁТ 3.36 и выше.
