### ISSUE TITLE
Бот не подключается к ЛЭРС учет

### ISSUE THREAD

**Issue by Abaddon7** [lers-uchet/LersBot#3]
> Если запрос не появляется, значит, бот не запустился или не подключился к серверу.

А из-за чего бот может не подключиться к серверу и как проверить подключение?
Я всё делал по Вашей инструкции, но единственное, при запуске службы "ЛЭРС учет - Служба поддержки сообщений Telegram" система выдает сообщение:
`Служба "ЛЭРС учет - Служба поддержки сообщений Telegram" на "Локальный компьютер" была запущена и затем остановлена. Некоторые службы автоматически останавливаются, если они не используются другими службами или программами`
ОС: Windows Server 2008 R2

**Comment by achikhv** [comment]
Для анализа проблемы нужен журнал C:\ProgramData\LERS\LersBot\bot.log

**Comment by Abaddon7** [comment]
Журнал прилагаю
[bot.zip](https://github.com/lers-uchet/LersBot/files/602535/bot.zip)

**Comment by achikhv** [comment]
Всё ясно, не хватает библиотеки. Распакуйте этот архив и положите файл System.Net.Http.Formatting.dll в папку C:\Program Files (x86)\LERS\LersBot\
[System.Net.Http.Formatting.dll.zip](https://github.com/lers-uchet/LersBot/files/602543/System.Net.Http.Formatting.dll.zip)

**Comment by Abaddon7** [comment]
Спасибо! Служба запустилась. Приглашение на авторизацию появилось.
А какие действия системы, если ввести неверный пароль от логина ЛЭРС учет?

**Comment by achikhv** [comment]
Должна быть выдана ошибка. После этого можете снова ввести команду /start и логин с паролем.

**Comment by Abaddon7** [comment]
Теперь служба снова не запускается.
Логи во вложении:
[bot.zip](https://github.com/lers-uchet/LersBot/files/602728/bot.zip)

**Comment by achikhv** [comment]
В журнале указана причина ошибки 

`21.11.2016 13:24:26	Info	Ошибка запуска бота. Lers.Networking.ServerConnectionException: Не удалось подключиться к серверу 192.128.1.21:10000.
Нет ответа от удаленного компьютера. Убедитесь, что адрес сервера указан правильно и служба "ЛЭРС УЧЕТ - Сервер" работает на удаленном компьютере. ---> System.Net.Sockets.SocketException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 192.128.1.21:10000
`

**Comment by Abaddon7** [comment]
Спасибо, разобрался. Почему-то изменился адрес сервера в файле bot.config, хотя я его не менял.
Стоял адрес 192.168.1.21:10000, а изменился на 192.128.1.21:10000.
