### ISSUE TITLE
Ошибка выполнения команды getcurrents

### ISSUE THREAD

**Issue by Abaddon7** [lers-uchet/LersBot#4]
При запросе текущих данных вылезает ошибка:
`Ошибка обработки команды. Не удалось загрузить тип "Lers.Data.MeasurePointConsumptionEventArgs" из сборки "Lers.System, Version=3.0.0.0, Culture=neutral, PublicKeyToken=e7c6d6299713498c".`

**Comment by achikhv** [comment]
Бот предназначен для работы с сервером версии 3.07 R20. Ошибка исчезнет после обновления.

**Comment by Abaddon7** [comment]
Обновился до R20, пишу команду /getcurrents, выдается ошибка:
```
Ошибка обработки команды. Не заданы критерии для поиска объектов
Имя параметра: criterias
```
Какой правильный синтаксис у команды?

**Comment by achikhv** [comment]
Это не ошибка, а сообщение о том, что параметры неверные.

После команды нужно набрать имя точки учёта, можно частичное.

Например, если у вас есть объект
"Мой объект" и в нём точка учёта "Теплоснабжение" вы можете выполнить команду
**/getcurrents мой объект тепло**

Точно такой же синтаксис у команд /nodes и /mpts.

Можете сначала проверить какая точка учёта будет выбрана командой /mpts. Если критерию удовлетворяет несколько точек учёта, текущие будут запрошены по первой в списке.
