### ISSUE TITLE
Обработка MessageType.

### ISSUE THREAD

**Issue by CliffordSimak** [lers-uchet/LersBot#8]
**Класс:** LersBot
**Метод**: Bot_OnMessage

- Если пользователь отправит в чат не текстовое сообщение, то метод
```
// Обрабатываем команду.
ProcessCommand(user, e.Message.Text);
```
выдаст _**System.ArgumentNullException**_.

- Предлагаю добавить проверку на **_MessageType_**.
```
// Обрабатываем команду.
if(e.Message.Type == MessageType.TextMessage)
      ProcessTextCommand(user);
```

**Comment by achikhv** [comment]
Спасибо за замечения, добавили обработку.
